version: "3.9"

services:
  pendulum-analysis:
    container_name: pendulum_oscillation_analysis
    build:
      context: .
      dockerfile: Dockerfile
    image: pendulum-oscillation-analysis:latest
    ports:
      - "8889:8889"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    restart: unless-stopped
